### ISSUE TITLE
Incorrect documentation for Kubernetes sidecar

### ISSUE THREAD

**Issue by erodewald** [ExpediaGroup/mittens#143]
**Describe the bug**

The [How To Run](https://expediagroup.github.io/mittens/docs/installation/running#run-as-a-sidecar-on-kubernetes) documentation indicates to the readers that:
1. they should use the `image: mittens:latest`, which is not valid.
2. they should set the `livenessProbe` to `cat ready` instead of `cat alive`

**To Reproduce**

n/a

**Expected behavior**

Documentation for Kubernetes as laid out will provide a working example

**Additional context**

Add any other context about the issue here.

**Comment by worldtiki** [comment]
Fixed in #144.

Thanks Eric!
