### ISSUE TITLE
Unable to use file probes when unable to run as root user

### ISSUE THREAD

**Issue by erodewald** [ExpediaGroup/mittens#146]
**Describe the bug**

In our Kubernetes environment, we set Pod-level security context to refuse any user to run as root. (see _figure A._)

**Figure A.**
```yaml
  podSecurityContext:
    runAsUser: 9999
    runAsGroup: 9999
    runAsNonRoot: true <-- this
    fsGroup: 9999
```

I have found that because the user expects to run as root and write to the root file system (see _figure B._), file probes do not work in our K8s environment. I suspect I could circumvent this if I could determine where the `ready` and `alive` files lived but it was removed in the spirit K.I.S.S. :) #106 

**Figure B.** (_output from a locally-operated docker container_)
```
/ # ls -lrt
total 64
drwxr-xr-x   11 root     root          4096 Mar  6  2019 var
drwxr-xr-x    7 root     root          4096 Mar  6  2019 usr
drwxrwxrwt    2 root     root          4096 Mar  6  2019 tmp
drwxr-xr-x    2 root     root          4096 Mar  6  2019 srv
drwxr-xr-x    2 root     root          4096 Mar  6  2019 sbin
drwxr-xr-x    2 root     root          4096 Mar  6  2019 run
drwxr-xr-x    2 root     root          4096 Mar  6  2019 mnt
drwxr-xr-x    5 root     root          4096 Mar  6  2019 media
drwxr-xr-x    5 root     root          4096 Mar  6  2019 lib
drwxr-xr-x    2 root     root          4096 Mar  6  2019 home
drwxr-xr-x    2 root     root          4096 Mar  6  2019 bin
drwxr-xr-x    2 root     root          4096 Nov 10 21:39 app
dr-xr-xr-x   13 root     root             0 Mar  2 21:57 sys
dr-xr-xr-x  156 root     root             0 Mar  2 21:57 proc
drwxr-xr-x    1 root     root          4096 Mar  2 21:57 etc
drwxr-xr-x    5 root     root           360 Mar  2 21:57 dev
-rw-r--r--    1 root     root             7 Mar  2 21:57 alive <---- this
drwx------    1 root     root          4096 Mar  2 21:58 root
-rw-r--r--    1 root     root             7 Mar  2 21:58 ready <----- this
/
```

**To Reproduce**

1. In K8s, set your `podSecurityContext` that forces the user to run as non-root
2. run mittens with file probes enabled
3. observe output: 
    > 2021/03/02 21:31:38 Writing file: ready
    > 2021/03/02 21:31:38 Writing to file failed with error: open ready: permission denied

**Expected behavior**

Dockerfile enables Mittens to run in a directory where it would have permission to write files, eliminating the need to revert #106 for edge cases.

**Additional context**

My initial impression would be to adopt common Dockerfile paradigms where:
1. a non-root user is created so we know the name
2. the user is granted ownership over the non-root fs directory
3. the user's workdir is set to non-root fs directory

**Comment by worldtiki** [comment]
Thanks for reporting this!

I opened a [draft](#147). I'm hoping to get some time tomorrow to validate this.

**Comment by erodewald** [comment]
Looks good, I'm leaving some comments on #147
