### ISSUE TITLE
Unit tests for util methods

### ISSUE THREAD

**Issue by nikos912000** [ExpediaGroup/mittens#172]
**Describe the feature**

We have a few relatively simple methods which are not unit tested. This includes methods in the following files:
- https://github.com/ExpediaGroup/mittens/blob/main/internal/pkg/internal/utils.go
- https://github.com/ExpediaGroup/mittens/blob/main/internal/pkg/probe/file.go

**Rational**

Writing tests for these methods provides an opportunity for first timers to contribute to open source and to get familiar with this codebase while at the same time adding value to this project.

**Comment by worldtiki** [comment]
Fixed by #174
