### ISSUE TITLE
Add support for arm64 architecture

### ISSUE THREAD

**Issue by rdomloge** [ExpediaGroup/mittens#182]
**Describe the feature**

Since the DockerHub image is not compatible with ARM, I tried to build the project myself on my rPi 4b running Ubuntu 20.04.2. The build failed during the testing phase with the message

> ?       mittens/pkg/warmup      [no test files]
> FAIL    mittens/test [build failed]
> FAIL
> make: *** [Makefile:7: test] Error 2

It would be great if the project was converted to multi-architecture or adapted to build on arm machines.

**Rational**

Mittens seems to be unique and I would really like to use it to warm pods on my Raspberry Pi Kubernetes cluster so that they can be brought into load fully warmed,  when the HPA scales out, since it does this under load and adding slower pods is less desirable. But I'm sure I am preaching to the converted!

**Comment by worldtiki** [comment]
Hi @rdomloge.

What version of go are you using? If you install golang using apt-get in raspbian you'll get 1.11 but Mittens needs 1.14.

**Comment by worldtiki** [comment]
ps: I pushed a docker image to my docker account that is compatible with raspberry's arch.

Do you mind giving it a try and see if it works?

```
docker run worldtiki/mittens:arch-all
```

![image](https://user-images.githubusercontent.com/1187103/125414091-7d9b332e-acd6-48b7-85b5-88639c0c98b2.png)

**Comment by rdomloge** [comment]
I'm using go1.13.8 which comes with that version of Ubuntu. Curiously, I followed a slightly different set of instructions on your site and ran 'make docker' which bypassed the unit tests and built the image perfectly. I'm now using it in my project.
Perhaps you could add the multi-arch image to your docker hub?

**Comment by rdomloge** [comment]
I also just tested your arch-all image and it works perfectly.

**Comment by worldtiki** [comment]
Yeap, the last version is now available on docker hub for multiple architectures https://hub.docker.com/r/expediagroup/mittens/tags?page=1&ordering=last_updated
