### ISSUE TITLE
Interpolate headers (use placeholders in http headers)

### ISSUE THREAD

**Issue by josepowera** [ExpediaGroup/mittens#204]
**Describe the feature**
Http headers sent during warmup phase would allow placeholders replacement (every line of sent http headers would go thru  InterpolatePlaceholders())

**Rational**

Allow to change http request headers per request

**Example Scenario**

We are warming up application and that includes caches that are enduser-browser cookie specific. In that case we would like to change value of "Cookies" that we send with 

`- "--http-headers=cookie: did=1458041116150878208"
`

in order to be able, to send http warmup requests for a range of users (cookies)

That means that

`- "--http-headers=cookie: did=145804111615087{$range|min=1000,max=9999}"`
would allow us, to send request for 9000 diffrent users.

Other examples that this feature would allow:
-replace http header UserAgent   to simulate different browser in order to warmup caches for user agent->device, platform,.. parsing
-replace http header  accept-language  to simulate different languages users are using and fetching translations
-replace http header  accept-encoding  to send both gzip and non gzip supported requests
-replace http header x-forwarded-for with different ips in order to warmup Geo IP resolving  example "({$range|min=1,max=255}.({$range|min=1,max=255}.1.15"

**Comment by worldtiki** [comment]
Thanks @josepowera 

I think it makes sense and it's a natural evolution of the current capabilities.
If you're happy to contribute a patch please go ahead :)

Otherwise someone will take a look at this as soon as we can.

**Comment by worldtiki** [comment]
Released in v1.27
