### ISSUE TITLE
HTTP/2 support incl. H2C

### ISSUE THREAD

**Issue by jrauschenbusch** [ExpediaGroup/mittens#322]
**Describe the feature**

Provide support for HTTP/2 incl. clear text protocol version

**Rational**

Newer web application use HTTP/2 instead of HTTP/1.1. Currently Mittens only supports HTTP/1.1, but also gRPC. It should be configurable which protocol version is used for HTTP requests. Furthermore as mittens is often used as sidecar, it should also support H2C protocol, as SSL/TLS is terminated most often in Proxy sidecars.

**Example Scenario**

Web application which uses HTTP/2

**Comment by jrauschenbusch** [comment]
@worldtiki Will there be a release of mittens to publish this feature?

**Comment by nikos912000** [comment]
@jrauschenbusch I was planning to do a release once we merge #335 if that's ok?
