### ISSUE TITLE
Improve recovery mechanism

### ISSUE THREAD

**Issue by nikos912000** [ExpediaGroup/mittens#82]
**Describe the feature**

By design mittens should never exit unless the `-exit-after-warmup` flag is set to true. This was a decision we made in order to avoid pod restarts in case of panic errors, i.e. the mittens container will be running indefinitely unless otherwise stated.

I've run into cases where panic errors cause it to exit. One such case is when the RPC service method doesn't exist which leads to the following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa342c9]

goroutine 40 [running]:
github.com/fullstorydev/grpcurl.InvokeRPC(0xd31480, 0xc00016e8d8, 0x0, 0x0, 0xd240c0, 0x0, 0x7ffe66ad6f65, 0x19, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.6.0/invoke.go:96 +0x199
mittens/pkg/grpc.(*Client).SendRequest(0xc000414f10, 0x7ffe66ad6f65, 0x19, 0x7ffe66ad6f7f, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mittens/pkg/grpc/client.go:108 +0x4bb
mittens/pkg/warmup.Warmup.GrpcWarmupWorker(0xc0002fb6e0, 0xc00035a480, 0x20, 0xc00035a4c0, 0x19, 0x0, 0x1, 0xc000356550, 0xc5b338, 0x0, ...)
	/mittens/pkg/warmup/warmup.go:59 +0x159
created by mittens/cmd.runWarmup
	/mittens/cmd/root.go:132 +0x407
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa342c9]

goroutine 42 [running]:
github.com/fullstorydev/grpcurl.InvokeRPC(0xd31480, 0xc00016e8d8, 0x0, 0x0, 0xd240c0, 0x0, 0x7ffe66ad6f65, 0x19, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.6.0/invoke.go:96 +0x199
mittens/pkg/grpc.(*Client).SendRequest(0xc00041af10, 0x7ffe66ad6f65, 0x19, 0x7ffe66ad6f7f, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mittens/pkg/grpc/client.go:108 +0x4bb
mittens/pkg/warmup.Warmup.GrpcWarmupWorker(0xc0002fb6e0, 0xc00035a480, 0x20, 0xc00035a4c0, 0x19, 0x0, 0x1, 0xc000356550, 0xc5b338, 0x0, ...)
	/mittens/pkg/warmup/warmup.go:59 +0x159
created by mittens/cmd.runWarmup
	/mittens/cmd/root.go:132 +0x407
```

It may be hard to catch all the cases where things can go wrong and doing so adds complexity to the code and hinders readability.
I was thinking we could use a better mechanism, such as the [defer/recover](https://blog.golang.org/defer-panic-and-recover) one. Note that this gets a bit tricky with goroutines.

**Rational**

The current implementation may cause issues in Kubernetes deployments. There is a chance that a panic error will terminate the mittens container and hence cause pod restarts. This may not be acceptable for our users.
Also, for readability purposes as mentioned above.

**Comment by ffeltrinelli** [comment]
I'm reasoning on this ticket and gathered some info, let me share.

As explained [in this article](https://golang.org/doc/effective_go.html#errors), any goroutine that is spawned at any point in the execution, has its own execution stack and if it panics, the execution is winded up on its stack, up to program termination, regardless of other goroutines. It's enough to have one goroutine that panics, among all the goroutines of the application, to crash the program.

Also, as confirmed [in this golang issue](https://github.com/golang/go/issues/20161), there's no way to have a global panic-catch-all mechanism. You have to safely execute every goroutine.

There seems to be two similar ways to achieve that:

1) `safelyDo`-like function

```
func safelyDo(work func()) {
    defer func() {
        if err := recover(); err != nil {
            log.Println("work failed:", err)
        }
    }()
    work()
}
```
which you then call with `go safelyDo(func() { .. })`.

2) `SafeGo`-like wrapper for the built in `go` operator

```
func SafeGo(f func()) {
	go func() {
		defer func() {
			if err := recover(); err != nil {
                                 log.Println("f failed:", err)
			}
		}()
		f()
	}()
}
```
which you then call with `SafeGo(func() { .. })`.

**Comment by ffeltrinelli** [comment]
I'm experimenting with approach 1, will raise a PR soon.

Note for myself: remember to add a comment on mittens docs mentioning that the target service needs grpc **reflection enabled**.
